FROM eclipse-temurin:17-alpine

RUN apk add file imagemagick ghostscript

# https://wiki.alpinelinux.org/wiki/Fonts
# removed (not found) : font-bitstream-* font-noto-* font-ipa
RUN apk add terminus-font ttf-inconsolata ttf-dejavu font-noto ttf-font-awesome font-noto-extra \
    font-vollkorn font-misc-cyrillic font-mutt-misc font-screen-cyrillic font-winitzki-cyrillic font-cronyx-cyrillic \
    font-noto-thai font-noto-tibetan font-sony-misc font-daewoo-misc font-jis-misc \
    font-isas-misc \
    font-noto-extra font-arabic-misc \
    font-misc-cyrillic font-mutt-misc font-screen-cyrillic font-winitzki-cyrillic font-cronyx-cyrillic \
    font-noto-arabic font-noto-armenian font-noto-cherokee font-noto-devanagari font-noto-ethiopic font-noto-georgian \
    font-noto-hebrew font-noto-lao font-noto-malayalam font-noto-tamil font-noto-thaana font-noto-thai
RUN fc-cache -fv
